name: Read hello.txt file

on:
  push:
    branches:
        - main

jobs:
  read-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Read hello.txt file
        run: |
          if [ -f hello.txt ]; then
            echo "Contents of hello.txt:"
            cat hello.txt
          else
            echo "hello.txt does not exist."
            fi

